# --------------------------------------- 
# Module: ee11-annotations
# Enables Annotation scanning for deployed web applications.
# --------------------------------------- 
--modules=ee11-annotations


